// <auto-generated />
namespace CrossyWords.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixDBFinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixDBFinal));
        
        string IMigrationMetadata.Id
        {
            get { return "201806110748085_FixDBFinal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
